language: node_js
node_js:
  - 'stable'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn

script:
  - rm -rf docs
  - yarn run build
  - mv build docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master
